### Добавление сотрудников из файа в БД
POST http://localhost:8080/employees/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="employees"; filename="employees.json"
Content-Type: application/json

< ./employees.json
--WebAppBoundary--